---
  Type: AWS::IAM::Role
  Properties:
    Path: /
    RoleName: ${self:custom.githubWebhookName}
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
              - edgelambda.amazonaws.com
          Action: sts:AssumeRole
    Policies:
      - PolicyName: ${self:custom.githubWebhookName}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
              Resource: "arn:aws:logs:*:*:*"
            - Effect: Allow
              Action:
                - cloudformation:DescribeStacks
                - cloudformation:DescribeAccountLimits
                - cloudformation:DescribeChangeSet
                - cloudformation:DescribeStackEvents
                - cloudformation:DescribeStackInstance
                - cloudformation:DescribeStackResource
                - cloudformation:DescribeStackResources
                - cloudformation:DescribeStackSet
                - cloudformation:DescribeStackSetOperation
                - cloudformation:EstimateTemplateCost
                - cloudformation:GetStackPolicy
                - cloudformation:GetTemplate
                - cloudformation:GetTemplateSummary
                - cloudformation:DeleteStack
                - iam:PassRole
              Resource: "*"           
            - Effect: Allow
              Action:
                - s3:*
              Resource: "*"