---
  Type: AWS::IAM::Role
  Properties:
    Path: /
    RoleName: ${self:custom.stackname}-viewerrequest
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
              - edgelambda.amazonaws.com
          Action: sts:AssumeRole
    Policies:
      - PolicyName: ${self:custom.stackname}-viewerrequest
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogStream
              Resource: 
                - "Fn::Join":
                  - ""
                  -
                    - "arn:aws:logs:"
                    - {Ref: "AWS::Region"}
                    - ":"
                    - {Ref: "AWS::AccountId"}
                    - ":log-group:/aws/lambda/"
                    - "${self:custom.stackname}-viewerRequest"
                    - ":*"
            - Effect: Allow
              Action:
                - logs:PutLogEvents
              Resource: 
                - "Fn::Join":
                  - ""
                  -
                    - "arn:aws:logs:"
                    - {Ref: "AWS::Region"}
                    - ":"
                    - {Ref: "AWS::AccountId"}
                    - ":log-group:/aws/lambda/"
                    - "${self:custom.stackname}-viewerRequest"
                    - ":*:*"
            - Effect: Allow
              Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
              Resource: "arn:aws:logs:*:*:*"
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:DescribeStream
                - dynamodb:GetRecords
                - dynamodb:GetShardIterator
                - dynamodb:ListStreams
              Resource:
                - "Fn::Join":
                    - ""
                    -
                      - "arn:aws:dynamodb:"
                      - {Ref: "AWS::Region"}
                      - ":"
                      - {Ref: "AWS::AccountId"}
                      - ":table/"
                      - ${self:custom.tablePrefix}
                - "Fn::Join":
                    - ""
                    -
                      - "arn:aws:dynamodb:"
                      - {Ref: "AWS::Region"}
                      - ":"
                      - {Ref: "AWS::AccountId"}
                      - ":table/"
                      - ${self:custom.tablePrefix}
                      - '/index/*'